# Generated by Django 4.2.7 on 2024-07-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mypage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(blank=True, null=True)),
                ('tid', models.CharField(max_length=40)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.CharField(max_length=300)),
            ],
        ),
    ]
