# Generated by Django 4.2.7 on 2024-07-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypage',
            name='tid',
        ),
        migrations.AlterField(
            model_name='mypage',
            name='content',
            field=models.TextField(),
        ),
    ]
