# Generated by Django 4.2.7 on 2024-07-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0003_mypage_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypage',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
