# Generated by Django 4.2.7 on 2024-09-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0010_alter_mypage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\django\\dream\\static\\images'),
        ),
    ]
