# Generated by Django 4.2.7 on 2024-09-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0012_alter_mypage_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypage',
            name='img',
        ),
        migrations.AddField(
            model_name='mypage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
