# Generated by Django 4.2.7 on 2024-09-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0013_remove_mypage_img_mypage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dairy/file/images'),
        ),
    ]
