# Generated by Django 4.2.7 on 2024-10-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0014_alter_mypage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
