# Generated by Django 4.2.7 on 2024-10-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0015_alter_mypage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mypage',
        ),
    ]
