# Generated by Django 4.2.7 on 2024-10-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0017_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=2000)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
